; rtos-hrt-firmware
; Human Reaction Timer — Arduino Uno R3 + FreeRTOS
; Author: George Mahfood | Baremetal Labs
; https://github.com/gmahfood/rtos-hrt-firmware

[env:uno]
platform  = atmelavr
board     = uno
framework = arduino

; Dependencies — installed automatically by PlatformIO
lib_deps =
    feilipu/FreeRTOS@^11.1.0-3
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    wayoda/LedControl@^1.0.6

monitor_speed   = 115200
monitor_filters = time, default
upload_speed    = 115200
