; rtos-hrt-firmware
; Human Reaction Timer — STM32F411 Black Pill + FreeRTOS
; Author: George Mahfood | Baremetal Labs
; https://github.com/gmahfood/rtos-hrt-firmware

[env:blackpill_f411ce]
platform  = ststm32
board     = blackpill_f411ce
framework = arduino

; Upload via ST-Link V2 over SWD
upload_protocol = stlink
debug_tool      = stlink

; Dependencies
lib_deps =
    stm32duino/STM32duino FreeRTOS@^10.3.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bodmer/TFT_eSPI@^2.5.43

; TFT_eSPI must be configured for ILI9488 — see docs/tft_setup.md
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DUSER_SETUP_LOADED=1
    -DILI9488_DRIVER=1
    -DTFT_MOSI=PA_7
    -DTFT_SCLK=PA_5
    -DTFT_CS=PA_4
    -DTFT_DC=PA_3
    -DTFT_RST=PC_5
    -DSPI_FREQUENCY=27000000

monitor_speed   = 115200
monitor_filters = time, default
upload_speed    = 115200